sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t freecloud2020/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true freecloud2020/docker-react npm run test
